apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  type: NodePort
  selector:
    app: sample
  ports:
    - port: 80
      targetPort: 80     # <--- match this to your containerPort
      nodePort: 30080
